### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by EnriqM** [JenniferBuehler/common-sensors#1]
Using [kinect.urdf.xacro](https://github.com/JenniferBuehler/common-sensors/blob/master/common_sensors/urdf/sensors/kinect.urdf.xacro) there is a problem: a file named 

> common_properties.urdf.xacro

 is missing, and it should be at the following path:

> ~/catkin_ws/src/common-sensors/common_sensors/urdf/common_properties.urdf.xacro

**Comment by JenniferBuehler** [comment]
Oh, sorry about this, I thought the file was obsolete so I didn't add it.

Thanks for reporting this. I haven't actually tried it again as I'm super tied up at the moment (hence my late reply as well, apologies). Can you try and see if it works now?

Thanks
Jenny

**Comment by EnriqM** [comment]
Hi,
I've been tied too, sorry for my late answer. You've just copied the missing file as I did to fix this, so I think it will work.
