### ISSUE TITLE
Not able to add Kinect to top-level xacro file

### ISSUE THREAD

**Issue by philwall3** [JenniferBuehler/common-sensors#2]
Hi,
thanks for that package.
How would I go about adding the kinect to my top-level xacro file? I want to fix the Kinect to the world frame. I'm quite new to this and haven't been succesful yet.

I've tried it like this:
```
<xacro:include filename="$(find common_sensors)/urdf/sensors/kinect.urdf.xacro" />
<joint name="kinect_joint" type="fixed">
	<parent link="world"/>
	<child link="camera_depth_frame"/>
	<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
</joint>
```

Sadly that doesn't seem to work, since I am getting this when trying to launch it into gazebo:

> [ERROR] [1511524465.083486378]: Failed to build tree: child link [camera_depth_frame] of joint [kinect_joint] not found
[...]
Error:   Failed to build tree: child link [camera_depth_frame] of joint [kinect_joint] not found
         at line 226 in /build/buildd/urdfdom-0.2.10+dfsg/urdf_parser/src/model.cpp
Error [parser_urdf.cc:2608] Unable to call parseURDF on robot model
Error [parser.cc:299] parse as old deprecated model file failed.
Error [World.cc:1527] Unable to read sdf string

Without the Kinect my robot is spawning nicely in gazebo.

Am I just not finding the correct base link or is there something else wrong with the way I try to use it?

Thanks!

**Comment by JenniferBuehler** [comment]
Hi,

I would suggest to attach the camera to your robot, not to the world. So make one of your robot's links the ``<parent link>``.
The kinect.urdf.xacro file offers a xacro macro ``sensor_kinect``, you will have to put it into your urdf, e.g. after the ``include`` directive:

``<xacro:sensor_kinect parent="your-robots-link"/>``

I haven't tried it because I'm just typing this from under way, but that should do it. If you're still having problems let me know and I can try it out on my computer as well.

**Comment by JenniferBuehler** [comment]
Ah and you don't need the joint that you declared then

**Comment by philwall3** [comment]
Thanks for your help!

The robot is a UR5 arm with a gripper attached, so attaching the Kinect onto that probably does not make too much sense. Attaching to the world is more or less the first test to get everything to work. It will probably not be the final position.

I've tried this as per your suggestion:
```
<xacro:include filename="$(find common_sensors)/urdf/sensors/kinect.urdf.xacro" />
<xacro:sensor_kinect parent="world"/>
```

And that's the output:

> phil@phil-VirtualBox:~$ roslaunch myrobot2_gazebo myrobot2.launch 
> ... logging to /home/phil/.ros/log/bb6a9e9e-d1c3-11e7-8249-080027c0668a/roslaunch-phil-VirtualBox-27705.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> Traceback (most recent call last):
>   File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
>     xacro.main()
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
>     eval_self_contained(doc)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
>     eval_all(doc.documentElement, macros, symbols)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 553, in eval_all
>     eval_all(body, macros, scoped)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 609, in eval_all
>     result = eval_text(at[1], symbols)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 483, in eval_text
>     results.append(handle_expr(lex.next()[1][2:-1]))
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 470, in handle_expr
>     return eval_expr(lex, symbols)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 444, in eval_expr
>     result = eval_term(lex, symbols)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 418, in eval_term
>     result = eval_factor(lex, symbols)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 398, in eval_factor
>     return neg * eval_lit(lex, symbols)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 369, in eval_lit
>     raise XacroException("Property wasn't defined: %s" % str(ex))
> xacro.XacroException: Property wasn't defined: u'cam_y'
> Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/phil/catkin_ws/src/myrobot2/myrobot2_description/urdf/myrobot2_macro.xacro' ] returned with code [1]. 
> 
> Param xml is <param command="$(find xacro)/xacro.py '$(find myrobot2_description)/urdf/myrobot2_macro.xacro' " name="robot_description"/>
> The traceback for the exception was written to the log file
> 
 
I've switched the cam_y with cam_py in the kinect.urdf.xacro (line 39 and 68) and that seems to have done the trick. The Kinect spawns in gazebo.

The position is a bit weird, but I have not investigated that yet:
<img width="1432" alt="virtualbox_2017-11-25_10-58-06" src="https://user-images.githubusercontent.com/27807006/33229462-abe1351c-d1cf-11e7-95dd-4e1450fc6ca2.png">

**Comment by JenniferBuehler** [comment]
Hi,
oh, thanks for uncovering this bug, no idea how this would have snug in. It's been a while I've used this package myself, not sure how this happened, weird... anyway``cam_py`` is the right spelling, ``cam_y`` does not exist. I have just updated this. Also I have changed the default orientation in kinect_properties.urdf.xacro (where you can adjust the orientation and pose of the camera) to a more common default, it must have had the values I needed for one of my projects.
Can you try again and see if that's better?

**Comment by philwall3** [comment]
Position of the Kinect is now normal as would be expected. Thanks again!
