### ISSUE TITLE
Split sensor description into a standalone package and make releases?

### ISSUE THREAD

**Issue by 130s** [JenniferBuehler/common-sensors#4]
FYI, being inspired by a few packages including yours, I created and [released a standalone package](https://discourse.ros.org/t/common-location-for-sensor-urdf-files/1758/4).

Looks like this repo contains description for more sensors. It'd be the most convenient for the global community if the desc of each sensor is separately available via binary. If you're curious to do that, I might be able to assist you (you can just simply copy and modify `openni_description` though).

**Comment by JenniferBuehler** [comment]
Hi, thanks for the suggestion.
So essentially you mean to separate the URDF's in this package into several separate packages? I've actually created this repo so all the common ones are together, because that's the sensors I most often use and I didn't want to always clone so many repositories ;)

**Comment by 130s** [comment]
> So essentially you mean to separate the URDF's in this package into several separate packages?

Yeah. I've updated the title to reflect my suggestion better.
By having each sensor model in separate packages and released, one that wants specific sensor model can simply depend on a very specific package without including sensor models that they don't need.

But it's totally up to you as it's your work :) Advantage for you might be that whatever improvements you might get from the community, and some credit for the opensource contribution.

**Comment by JenniferBuehler** [comment]
Yes it would probably be nice to split them for doing releases, but I'd still keep this collection as one repository as well, as I've created it with the purpose to have the most common sensors in one package. Some of the URDFs are also modifications of existing URDFs (see README) which may already be released (I haven't checked though). I've intended this collection more as a convenience bundle - for official releases of my modifications one should probably confirm with the authors of the URDFs this package is based on - if not required for the license then at least out of courtesy ;)

**Comment by 130s** [comment]
Ok! This was just a friendly headsup :)

**Comment by JenniferBuehler** [comment]
Yes thanks for the feedback :) I'll consider adding separate packages too. Cheers!
