### ISSUE TITLE
Expected Constructor, destructor or type conversion error originating from filters.cpp

### ISSUE THREAD

**Issue by jproberge** [JenniferBuehler/common-sensors#8]
Hi, 

I haven't taken the time to really investigate, but I was able to get the exact same error on two different machines running ros-melodic on Ubuntu 18.04. The error is shown below:

![Screenshot from 2019-04-24 18-55-13](https://user-images.githubusercontent.com/5903636/56699318-06c8f580-66c3-11e9-8e5a-790c6dc83a52.png)

I've installed all the dependencies and followed the installation procedure described in the ReadMe. Perhaps this is an compatibility error with pluginlib?

**Comment by jproberge** [comment]
I'm sorry, I'm closing this issue, I've just seen there is a PR addressing this issue. I think it should be merged to the main branch.

Thanks!

**Comment by JenniferBuehler** [comment]
I guess you are refering to [PR 5](https://github.com/JenniferBuehler/common-sensors/pull/5)? Yes I have already edited this PR and am awaiting the merge of my edits [here](https://github.com/joao-pm-santos96/common-sensors/pull/1). I will ask again whether this can be merged, if I don't get a response soon then I'll just merge my changes directly.

I you can find all the required changes in the branch `jaosantos_master`
